#!/bin/bash
set -e
source ./vars.sh

swap_size=4096
efi_size=2048

# Partitioning the Disk
printf "Partitioning $R_DISK...\n"
parted $R_DISK mklabel gpt

# Create the swap partition
printf "Creating swap partition...\n"
parted $R_DISK mkpart primary linux-swap 1MiB ${swap_size}MiB
parted $R_DISK set 1 swap on

# Create the EFI partition
printf "Creating EFI partition...\n"
parted $R_DISK mkpart ESP fat32 ${swap_size}MiB $((swap_size + efi_size))MiB
parted $R_DISK set 2 boot on

# Create the root partition
printf "Creating root partition...\n"
parted $R_DISK mkpart primary $R_ROOT_PARTITION_FORMAT $((swap_size + efi_size + 1))MiB 100%

printf "Partitioning complete.\n"
