#!/bin/bash
read -p "Swap partition: " swap_partition
read -p "Efi partition: " efi_partition
read -p "Ext4 partition: " ext4_partition


mkfs.ext4 $ext4_partition &&
mkfs.fat -F 32 $efi_partition &&
mkswap $swap_partition &&
mount $ext4_partition /mnt &&
mkdir /mnt/boot/efi -p &&
mount $efi_partition /mnt/boot/efi &&
pacstrap /mnt base base-devel linux linux-firmware nano bash-completion &&
genfstab -U -p /mnt >> /mnt/etc/fstab &&
cp -r . /mnt/archinstall
