#!/bin/bash
swap_partition=/dev/sdc1
efi_partition=/dev/sdc2
ext4_partition=/dev/sdc3
efi_mount=/mnt/boot/efi

btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
umount /mnt
mount -o compress=zstd,subvol=@ $ext4_partition /mnt
mkdir /mnt/home
mount -o compress=zstd,subvol=@home $ext4_partition /mnt/home &&
mkdir $efi_mount -p &&
mount $efi_partition $efi_mount

