#!/bin/bash
pacman -S grub-efi-x86_64 efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch_grub --recheck
cp /usr/share/locale/en@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
mypath=/etc/default/grub
sed -i "s/#\?\(GRUB_DISABLE_OS_PROBER=false\)/\1/" "$mypath"
grub-mkconfig -o /boot/grub/grub.cfg
