#!/bin/bash

myenv=kde
nvidia=true

pacman -S xorg firefox vlc
if [ nvidia ]; then
    pacman -S nvidia nvidia-libgl mesa
fi

case "$myenv" in
    kde)
        pacman -S sddm plasma konsole dolphin ark okular partitionmanager transmission-qt
        systemctl enable sddm
        ;;
    gnome)
        pacman -S gnome gnome-terminal firefox gdm
        systemctl enable gdm
        ;;
    *)
        echo "not found"
        ;;
esac

