#!/bin/bash
pacman -S --needed --noconfirm base-devel git clang zip unzip flameshot freerdp docker docker-compose rclone libreoffice-fresh libreoffice-fresh-pt-br postgresql-libs python-pip openssl xz tk flatpak vlc obs-studio openssh ufw --noconfirm && \
pacman -S --needed --noconfirm kdeconnect
systemctl enable docker.service --now
usermod -aG docker renato
systemctl enable zerotier-one.service --now
systemctl enable sshd --now
ufw allow ssh

pacman -S --needed --noconfirm qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat edk2-ovmf swtpm qemu-hw-usb-host usbutils &&
pacman -S --needed --noconfirm qemu-ui-spice-core qemu-ui-spice-app qemu-hw-usb-redirect qemu-audio-spice qemu-hw-display-qxl &&
pacman -S --needed  ebtables iptables
systemctl enable libvirtd.service &&
systemctl start libvirtd.service
mypath=/etc/libvirt/libvirtd.conf
sed -i "s/#\?\(unix_sock_group\)/\1/" "$mypath"
sed -i "s/#\?\(unix_sock_rw_perms\)/\1/" "$mypath"
usermod -a -G libvirt renato
newgrp libvirt 
systemctl restart libvirtd.service 

